// flow-typed signature: 37d06c4564a099d57e7231f53195ba78
// flow-typed version: <<STUB>>/validate-npm-package-name_v^3.0.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'validate-npm-package-name'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'validate-npm-package-name' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'validate-npm-package-name/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'validate-npm-package-name/index' {
  declare module.exports: $Exports<'validate-npm-package-name'>;
}
declare module 'validate-npm-package-name/index.js' {
  declare module.exports: $Exports<'validate-npm-package-name'>;
}
declare module 'validate-npm-package-name/test/index.js' {
  declare module.exports: $Exports<'validate-npm-package-name/test/index'>;
}
