export const haste = [
  'ARTSerializablePath',
  'ActionSheetIOS',
  'ActivityIndicator',
  'Alert',
  'AlertIOS',
  'Animated',
  'AnimatedAddition',
  'AnimatedDiffClamp',
  'AnimatedDivision',
  'AnimatedEvent',
  'AnimatedImplementation',
  'AnimatedInterpolation',
  'AnimatedModulo',
  'AnimatedMultiplication',
  'AnimatedNode',
  'AnimatedProps',
  'AnimatedStyle',
  'AnimatedTracking',
  'AnimatedTransform',
  'AnimatedValue',
  'AnimatedValueXY',
  'AnimatedWeb',
  'AnimatedWithChildren',
  'Animation',
  'AppContainer',
  'AppRegistry',
  'AppState',
  'Array.es6',
  'Array.prototype.es6',
  'AssetRegistry',
  'AssetSourceResolver',
  'AsyncStorage',
  'BackAndroid',
  'BatchedBridge',
  'Batchinator',
  'Blob',
  'BlobTypes',
  'BorderBox',
  'BoundingDimensions',
  'BugReporting',
  'Button',
  'CameraRoll',
  'Clipboard',
  'ColorPropType',
  'DebugEnvironment',
  'DecayAnimation',
  'DeviceInfo',
  'Dimensions',
  'DocumentSelectionState',
  'Easing',
  'EdgeInsetsPropType',
  'ElementBox',
  'ElementProperties',
  'EmitterSubscription',
  'ErrorUtils',
  'EventEmitter',
  'EventEmitterWithHolding',
  'EventHolder',
  'EventSubscription',
  'EventSubscriptionVendor',
  'EventValidator',
  'ExceptionsManager',
  'FillRateHelper',
  'FlatList',
  'FormData',
  'FrameRateLogger',
  'Geolocation',
  'HMRClient',
  'HeapCapture',
  'I18nManager',
  'ImageBackground',
  'ImageEditor',
  'ImagePickerIOS',
  'ImageResizeMode',
  'ImageSource',
  'ImageSourcePropType',
  'ImageStore',
  'ImageStylePropTypes',
  'Incremental',
  'IncrementalGroup',
  'IncrementalPresenter',
  'InitializeCore',
  'InspectorAgent',
  'InspectorOverlay',
  'InspectorPanel',
  'InteractionManager',
  'InteractionMixin',
  'JSEventLoopWatchdog',
  'JSTimers',
  'Keyboard',
  'KeyboardAvoidingView',
  'LayoutAnimation',
  'LayoutPropTypes',
  'LazyRenderer',
  'Linking',
  'ListView',
  'ListViewDataSource',
  'Map',
  'MatrixMath',
  'MessageQueue',
  'MetroListView',
  'MissingNativeEventEmitterShim',
  'Modal',
  'NativeAnimatedHelper',
  'NativeEventEmitter',
  'NativeMethodsMixin',
  'NativeModules',
  'NetInfo',
  'NetworkAgent',
  'NetworkOverlay',
  'Number.es6',
  'Object.es6',
  'Object.es7',
  'PanResponder',
  'PerformanceLogger',
  'PerformanceOverlay',
  'PermissionsAndroid',
  'Picker',
  'PixelRatio',
  'PointPropType',
  'PooledClass',
  'Position',
  'Promise',
  'QuickPerformanceLogger',
  'RCTDeviceEventEmitter',
  'RCTEventEmitter',
  'RCTLog',
  'RCTNativeAppEventEmitter',
  'React',
  'ReactDebugTool',
  'ReactGlobalSharedState',
  'ReactNative',
  'ReactNativeART',
  'ReactNativeBridgeEventPlugin',
  'ReactNativeComponentTree',
  'ReactNativeFeatureFlags',
  'ReactNativePropRegistry',
  'ReactNativeStyleAttributes',
  'ReactNativeTypes',
  'ReactNativeVersion',
  'ReactNativeVersionCheck',
  'ReactNativeViewAttributes',
  'ReactPerf',
  'ReactTypes',
  'RefreshControl',
  'RelativeImageStub',
  'SamplingProfiler',
  'SceneTracker',
  'ScrollResponder',
  'ScrollView',
  'ScrollViewStickyHeader',
  'SectionList',
  'Set',
  'ShadowPropTypesIOS',
  'Share',
  'Slider',
  'SpringAnimation',
  'SpringConfig',
  'StaticContainer.react',
  'StaticRenderer',
  'StatusBar',
  'String.prototype.es6',
  'StyleSheet',
  'StyleSheetPropType',
  'StyleSheetTypes',
  'StyleSheetValidation',
  'Subscribable',
  'SwipeableFlatList',
  'SwipeableListView',
  'SwipeableListViewDataSource',
  'SwipeableQuickActionButton',
  'SwipeableQuickActions',
  'SwipeableRow',
  'Switch',
  'Systrace',
  'TVViewPropTypes',
  'TaskQueue',
  'Text',
  'TextInput',
  'TextInputState',
  'TextStylePropTypes',
  'TextUpdateTest',
  'TimingAnimation',
  'TouchHistoryMath',
  'Touchable',
  'TouchableBounce',
  'TouchableHighlight',
  'TouchableOpacity',
  'TouchableWithoutFeedback',
  'TransformPropTypes',
  'UIManager',
  'UIManagerStatTracker',
  'URL',
  'UnimplementedView',
  'Vibration',
  'View',
  'ViewAccessibility',
  'ViewPropTypes',
  'ViewStylePropTypes',
  'ViewabilityHelper',
  'VirtualizeUtils',
  'VirtualizedList',
  'VirtualizedSectionList',
  'WebSocket',
  'WebSocketEvent',
  'WebSocketInterceptor',
  'WindowedListView',
  'XHRInterceptor',
  'XMLHttpRequest',
  'YellowBox',
  '_shouldPolyfillES6Collection',
  'babelHelpers',
  'bezier',
  'binaryToBase64',
  'buildStyleInterpolator',
  'clamp',
  'console',
  'convertRequestBody',
  'createAnimatedComponent',
  'createReactNativeComponentClass',
  'createStrictShapeTypeChecker',
  'deepDiffer',
  'deepFreezeAndThrowOnMutationInDev',
  'defineLazyObjectProperty',
  'deprecatedPropType',
  'dismissKeyboard',
  'dumpReactTree',
  'ensureComponentIsNative',
  'ensurePositiveDelayProps',
  'error-guard',
  'fetch',
  'flattenStyle',
  'getDevServer',
  'getObjectValues',
  'getReactData',
  'groupByEveryN',
  'guid',
  'infoLog',
  'insetsDiffer',
  'isEmpty',
  'logError',
  'mapWithSeparator',
  'matricesDiffer',
  'merge',
  'mergeFast',
  'mergeHelpers',
  'mergeInto',
  'mergeIntoFast',
  'mixInEventEmitter',
  'nativeImageSource',
  'normalizeColor',
  'openFileInEditor',
  'parseErrorStack',
  'pointsDiffer',
  'processColor',
  'processDecelerationRate',
  'processTransform',
  'promiseRejectionIsError',
  'queryLayoutByID',
  'react-native-implementation',
  'react-native-interface',
  'renderApplication',
  'requireNativeComponent',
  'resolveAssetSource',
  'resolveBoxStyle',
  'setNormalizedColorAlpha',
  'setupDevtools',
  'sizesDiffer',
  'stringifySafe',
  'symbolicateStackTrace',
  'takeSnapshot',
  'toIterator',
  'truncate',
  'utf8',
  'verifyPropTypes',
  'AccessibilityInfo',
  'BackHandler',
  'CheckBox',
  'DatePickerAndroid',
  'DatePickerIOS',
  'DrawerLayoutAndroid',
  'HMRLoadingView',
  'Image',
  'MaskedViewIOS',
  'NavigatorIOS',
  'PickerAndroid',
  'PickerIOS',
  'Platform',
  'PlatformViewPropTypes',
  'ProgressBarAndroid',
  'ProgressViewIOS',
  'RCTAlertManager',
  'RCTNetworking',
  'SafeAreaView',
  'Sample',
  'SegmentedControlIOS',
  'Settings',
  'SnapshotViewIOS',
  'StatusBarIOS',
  'TVEventHandler',
  'TabBarIOS',
  'TabBarItemIOS',
  'TimePickerAndroid',
  'ToastAndroid',
  'ToolbarAndroid',
  'TouchableNativeFeedback',
  'VibrationIOS',
  'ViewPagerAndroid',
  'WebView',
  'react-native/Libraries/ART/ReactNativeART',
  'react-native/Libraries/Renderer/shims/ReactNativePropRegistry',
  'react-native/package',
];

export const aliases = {
  // @expo/snack-static/react-native-logo.png is an alias that is
  // implemented in the runtime, and uses by the react-native image docs
  '@expo/snack-static': '0.0.1',
  '@expo/snack-static/react-native-logo.png': '0.0.1',
};

export const dependencies = {
  '36.0.0': {
    ...aliases,
    '@expo/vector-icons': '10.0.0',
    '@unimodules/core': '5.0.0',
    '@unimodules/react-native-adapter': '5.0.0',
    expo: '36.0.0',
    'expo-asset': '8.0.0',
    'expo-auth-session': '1.0.0',
    'expo-barcode-scanner': '8.0.0',
    'expo-camera': '8.0.0',
    'expo-constants': '8.0.0',
    'expo-file-system': '8.0.0',
    'expo-font': '8.0.0',
    'expo-gl': '8.0.0',
    'expo-image-picker': '8.0.0',
    'expo-linear-gradient': '8.0.0',
    react: '16.9.0',
    'react-native': '0.61.4',
    'prop-types': '15.7.2',
    'react-dom': '16.9.0',
    'react-native-web': '0.11.7',
    'react-native-gesture-handler': '1.5.0',
    'unimodules-permissions-interface': '5.0.0',
  },
  '37.0.0': {
    ...aliases,
    '@expo/vector-icons': '10.0.0',
    '@unimodules/core': '5.1.0',
    '@unimodules/react-native-adapter': '5.1.1',
    expo: '37.0.0',
    'expo-asset': '8.1.1',
    'expo-barcode-scanner': '8.1.0',
    'expo-camera': '8.2.0',
    'expo-constants': '9.0.0',
    'expo-file-system': '8.1.0',
    'expo-font': '8.1.0',
    'expo-gl': '8.1.0',
    'expo-image-picker': '8.1.0',
    'expo-linear-gradient': '8.1.0',
    react: '16.9.0',
    'react-native': '0.61.4',
    'prop-types': '15.7.2',
    'react-dom': '16.9.0',
    'react-native-web': '0.11.7',
    'react-native-gesture-handler': '1.6.0',
    'unimodules-permissions-interface': '5.1.0',
  },
  // The outcommented dependencies are also preloaded in the runtime, however we don't mark them
  // as such, so that the snack-sdk will allow adding them to the package.json dependencies.
  // When any of these dependencies is sent to the runtime, the version is ignored and the
  // runtime uses the version that was bundled into the runtime instead.
  '38.0.0': {
    ...aliases,
    expo: '38.0.1',
    react: '16.11.0',
    'react-native': '0.62.2',
    'react-dom': '16.11.0',
    'react-native-web': '0.11.7',
    // Packages that require special initialisation (see Modules.tsx)
    'expo-asset': '8.1.7',
    'react-native-gesture-handler': '1.6.0',
    //'react-native-vector-icons': '10.0.0',
    '@expo/vector-icons': '10.0.0',
    // Packages that are used internally by the runtime
    //'expo-analytics-amplitude': '8.2.1',
    'expo-barcode-scanner': '8.2.1',
    'expo-constants': '9.1.1',
    'expo-file-system': '9.0.1',
    //'expo-keep-awake': '8.2.1',
    'react-native-view-shot': '3.1.2',
    // Packages that are depended on by one of the packages above
    'expo-font': '8.2.1', // used by "expo"
    //'expo-linking': '1.0.3', // used by "expo"
    //'expo-permissions': '9.0.1', // used by "expo"
    //'expo-splash-screen': '0.3.1', // used by "expo"
    'prop-types': '15.7.2', // *
    '@unimodules/core': '5.3.0', // used by "expo"
    '@unimodules/react-native-adapter': '5.4.0', // used by "expo"
    'unimodules-permissions-interface': '5.2.1', // used by "expo"
    // Packages that are not really required
    // TODO: THESE SHOULD BE REMOVED ONCE THE SNACK-SDK HANDLES ADDING/REMOVING/UPDATING DEPENDENCIES BETTER
    'expo-camera': '8.3.1',
    'expo-gl': '8.3.1',
    'expo-image-picker': '8.3.0',
    'expo-linear-gradient': '8.2.1',
  },
  // The outcommented dependencies are also preloaded in the runtime, however we don't mark them
  // as such, so that the snack-sdk will allow adding them to the package.json dependencies.
  // When any of these dependencies is sent to the runtime, the version is ignored and the
  // runtime uses the version that was bundled into the runtime instead.
  '39.0.0': {
    ...aliases,
    expo: '39.0.2',
    react: '16.13.1',
    'react-native': '0.63.2',
    'react-dom': '16.13.1',
    'react-native-web': '0.13.12',
    // Packages that require special initialisation (see Modules.tsx)
    'expo-asset': '8.2.0',
    'react-native-gesture-handler': '1.7.0',
    //'react-native-vector-icons': '10.0.0',
    '@expo/vector-icons': '10.0.0',
    // Packages that are used internally by the runtime
    'expo-barcode-scanner': '9.0.0',
    'expo-constants': '9.2.0',
    'expo-file-system': '9.2.0',
    'react-native-view-shot': '3.1.2',
    // Packages that are depended on by one of the packages above
    'expo-font': '8.3.0', // used by "expo"
    'prop-types': '15.7.2', // *
    '@unimodules/core': '5.5.0', // used by "expo"
    '@unimodules/react-native-adapter': '5.6.0', // used by "expo"
    'unimodules-permissions-interface': '5.3.0', // used by "expo"
    // Packages that are not really required
    // TODO: THESE SHOULD BE REMOVED ONCE THE SNACK-SDK HANDLES ADDING/REMOVING/UPDATING DEPENDENCIES BETTER
    'expo-camera': '9.0.0',
    'expo-gl': '9.1.1',
    'expo-image-picker': '9.1.1',
    'expo-linear-gradient': '8.3.0',
  },
};
