apiVersion: apps/v1
kind: Deployment
metadata:
  name: snackpub
spec:
  template:
    spec:
      nodeSelector:
        pool: dev
      tolerations:
      - key: dedicated
        value: dev
        effect: NoSchedule
