apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../base
  - external-secret-env.yaml
patchesStrategicMerge:
  - service-backend.yaml
secretGenerator:
  - name: snackpub-env
    behavior: merge
    files:
      - ./external-secret-env.yaml
