apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../base
patchesStrategicMerge:
  - service-backend.yaml
secretGenerator:
  - name: snackpub-env
    envs:
      - secrets/snackpub.env
