name: Setup Snackager
description: Prepare Snackager in GitHub Actions

inputs:
  python-version:
    description: Python version to use when installing Google Cloud SDK
    default: '2.7'

  project-id:
    description: Google Cloud SDK project id
    default: exponentjs

  project-zone:
    description: Google Cloud SDK compute zone
    default: us-central1-f

  project-cluster:
    description: Google Cloud SDK container cluster
    default: exp-central

  service-key:
    description: Google Cloud SDK service_account_key
    required: true

  export-default-credentials:
    type: boolean
    description: If it should export the default credentials
    default: true

runs:
  using: composite
  steps:
    - name: 🏗 Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    
    - name: 🏗 Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        project_id: ${{ inputs.project-id }}
        service_account_key: ${{ inputs.service-key }}
        export_default_credentials: ${{ inputs.export-default-credentials }}

    - name: 📦 Install Google Cloud SDK components
      run: gcloud components install kubectl kustomize skaffold
      shell: bash

    - name: ⚙️ Configure Google Cloud SDK
      run: |
        gcloud config set project ${{ inputs.project-id }}
        gcloud config set compute/zone ${{ inputs.project-zone }}
        gcloud config set container/cluster ${{ inputs.project-cluster }}
        gcloud container clusters get-credentials ${{ inputs.project-cluster }}
        gcloud auth configure-docker gcr.io
      shell: bash
