apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: snackpub
resources:
  - deployment.yaml
  - service.yaml
configurations:
  - external-secrets-config.yaml
secretGenerator:
- name: snackpub-env
