apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- ingress.yaml
- service.yaml
commonLabels:
  app: snack
configMapGenerator:
- name: snack
secretGenerator:
- name: snack
  envs:
  - secrets/snack.env
