apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- ../base
- vertical-pod-autoscaler.yaml
patchesStrategicMerge:
- deployment-replicas.yaml
- service-backend.yaml
configMapGenerator:
- name: snack
  behavior: merge
  envs:
  - snack.env
