apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: snack
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       snack
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
    - containerName: snack
      maxAllowed:
        cpu: 600m
        memory: 1500Mi
