apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snackager
spec:
  rules:
    - host: snackager.expo.test
      http:
        paths:
        - backend:
            service:
              name: snackager
              port:
                number: 80
          path: /
