apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- ../staging
patches:
- path: deployment-delay-probes.yaml
- patch: |-
    - op: remove
      path: /spec/template/spec/containers/0/resources
  target:
    group: apps
    kind: Deployment
    name: snackager
    version: v1
configMapGenerator:
- name: snackager-config
  behavior: merge
  literals:
  - DEBUG_LOCAL_FILES=true
  - DISABLE_INSTRUMENTATION=1
  - NODE_ENV=development
