---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: git-account-credentials
spec:
  refreshInterval: "0"
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: snackager-config
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: production__snack__snackager__gh_private_key
      version: "1"
