name: "\U0001F4C3 Documentation Bug"
about: 'You want to report something that is wrong or missing from the documentation.'
issue_body: true
title: '[docs] '
labels: 'project: docs'
inputs:
  - type: description
    attributes:
      value: Thanks for helping us make Expo Snack even better! We want our docs to be an amazing resource, and that requires your feedback!
  - type: textarea
    attributes:
      label: Summary
      required: true
      description: Clearly describe what is wrong or missing from the docs.
  - type: input
    attributes:
      label: Link to the related docs page
      required: false
  - type: description
    attributes:
      value: If this is a typo, or something you feel up to fixing, please do so! You can edit any page in our docs by scrolling to the bottom and selecting `Edit this page`.
