name: "\U0001F64B Feature Request"
about: 'Want us to add something to Expo Snack?'
issue_body: false
inputs:
  - type: description
    attributes:
      value: Thanks for helping us make Expo Snack even better! 😀 Unfortunately, this is not the right place for feature requests. Please find and upvote your feature (or create a new one) at https://expo.canny.io instead.
  - type: dropdown
    attributes:
      label: Do you understand that any feature requests opened in the core Expo Snack repository will be closed?
      required: true
      choices:
        - Yes
