apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
bases:
- ../base
patchesStrategicMerge:
- service-backend.yaml
configMapGenerator:
- name: snack
  behavior: merge
  envs:
  - snack.env
