apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: snackpub
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       snackpub
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
    - containerName: snackpub
      maxAllowed:
        cpu: 1000m
        memory: 1.5Gi
