// flow-typed signature: c2d9958f030d4f960233b48bf81d2e99
// flow-typed version: <<STUB>>/gulp-plumber_v^1.1.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-plumber'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-plumber' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-plumber/index' {
  declare module.exports: $Exports<'gulp-plumber'>;
}
declare module 'gulp-plumber/index.js' {
  declare module.exports: $Exports<'gulp-plumber'>;
}
