// flow-typed signature: b368ceb9ac0ae666a77d9b45edf75f8b
// flow-typed version: <<STUB>>/pubnub_v^4.3.3/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pubnub'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pubnub' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pubnub/dist/titanium/pubnub' {
  declare module.exports: any;
}

declare module 'pubnub/dist/titanium/pubnub.min' {
  declare module.exports: any;
}

declare module 'pubnub/dist/web/pubnub' {
  declare module.exports: any;
}

declare module 'pubnub/dist/web/pubnub.min' {
  declare module.exports: any;
}

declare module 'pubnub/gulpfile.babel' {
  declare module.exports: any;
}

declare module 'pubnub/karma/coverage/PhantomJS 2.1.1 (Mac OS X 0.0.0)/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'pubnub/karma/coverage/PhantomJS 2.1.1 (Mac OS X 0.0.0)/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'pubnub/karma/coverage/PhantomJS 2.1.1 (Mac OS X 0.0.0)/prettify' {
  declare module.exports: any;
}

declare module 'pubnub/karma/coverage/PhantomJS 2.1.1 (Mac OS X 0.0.0)/sorter' {
  declare module.exports: any;
}

declare module 'pubnub/karma/titanium.config' {
  declare module.exports: any;
}

declare module 'pubnub/karma/web.config' {
  declare module.exports: any;
}

declare module 'pubnub/lib/core/components/config' {
  declare module.exports: any;
}

declare module 'pubnub/lib/core/components/cryptography/hmac-sha256' {
  declare module.exports: any;
}

declare module 'pubnub/lib/core/components/cryptography/index' {
  declare module.exports: any;
}

declare module 'pubnub/lib/core/components/endpoint' {
  declare module.exports: any;
}

declare module 'pubnub/lib/core/components/listener_manager' {
  declare module.exports: any;
}

declare module 'pubnub/lib/core/components/reconnection_manager' {
  declare module.exports: any;
}

declare module 'pubnub/lib/core/components/subscription_manager' {
  declare module.exports: any;
}

declare module 'pubnub/lib/core/constants/categories' {
  declare module.exports: any;
}

declare module 'pubnub/lib/core/constants/operations' {
  declare module.exports: any;
}

declare module 'pubnub/lib/core/endpoints/access_manager/audit' {
  declare module.exports: any;
}

declare module 'pubnub/lib/core/endpoints/access_manager/grant' {
  declare module.exports: any;
}

declare module 'pubnub/lib/core/endpoints/channel_groups/add_channels' {
  declare module.exports: any;
}

declare module 'pubnub/lib/core/endpoints/channel_groups/delete_group' {
  declare module.exports: any;
}

declare module 'pubnub/lib/core/endpoints/channel_groups/list_channels' {
  declare module.exports: any;
}

declare module 'pubnub/lib/core/endpoints/channel_groups/list_groups' {
  declare module.exports: any;
}

declare module 'pubnub/lib/core/endpoints/channel_groups/remove_channels' {
  declare module.exports: any;
}

declare module 'pubnub/lib/core/endpoints/fetch_messages' {
  declare module.exports: any;
}

declare module 'pubnub/lib/core/endpoints/history' {
  declare module.exports: any;
}

declare module 'pubnub/lib/core/endpoints/presence/get_state' {
  declare module.exports: any;
}

declare module 'pubnub/lib/core/endpoints/presence/heartbeat' {
  declare module.exports: any;
}

declare module 'pubnub/lib/core/endpoints/presence/here_now' {
  declare module.exports: any;
}

declare module 'pubnub/lib/core/endpoints/presence/leave' {
  declare module.exports: any;
}

declare module 'pubnub/lib/core/endpoints/presence/set_state' {
  declare module.exports: any;
}

declare module 'pubnub/lib/core/endpoints/presence/where_now' {
  declare module.exports: any;
}

declare module 'pubnub/lib/core/endpoints/publish' {
  declare module.exports: any;
}

declare module 'pubnub/lib/core/endpoints/push/add_push_channels' {
  declare module.exports: any;
}

declare module 'pubnub/lib/core/endpoints/push/list_push_channels' {
  declare module.exports: any;
}

declare module 'pubnub/lib/core/endpoints/push/remove_device' {
  declare module.exports: any;
}

declare module 'pubnub/lib/core/endpoints/push/remove_push_channels' {
  declare module.exports: any;
}

declare module 'pubnub/lib/core/endpoints/subscribe' {
  declare module.exports: any;
}

declare module 'pubnub/lib/core/endpoints/time' {
  declare module.exports: any;
}

declare module 'pubnub/lib/core/flow_interfaces' {
  declare module.exports: any;
}

declare module 'pubnub/lib/core/pubnub-common' {
  declare module.exports: any;
}

declare module 'pubnub/lib/core/utils' {
  declare module.exports: any;
}

declare module 'pubnub/lib/db/common' {
  declare module.exports: any;
}

declare module 'pubnub/lib/db/web' {
  declare module.exports: any;
}

declare module 'pubnub/lib/networking/index' {
  declare module.exports: any;
}

declare module 'pubnub/lib/networking/modules/node' {
  declare module.exports: any;
}

declare module 'pubnub/lib/networking/modules/react_native' {
  declare module.exports: any;
}

declare module 'pubnub/lib/networking/modules/titanium' {
  declare module.exports: any;
}

declare module 'pubnub/lib/networking/modules/web-node' {
  declare module.exports: any;
}

declare module 'pubnub/lib/networking/utils' {
  declare module.exports: any;
}

declare module 'pubnub/lib/node/index' {
  declare module.exports: any;
}

declare module 'pubnub/lib/react_native/index' {
  declare module.exports: any;
}

declare module 'pubnub/lib/titanium/index' {
  declare module.exports: any;
}

declare module 'pubnub/lib/web/index' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/analytics' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/browser' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/colors' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/css' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/declare' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/dom' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/encoding' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/event' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/Evented' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/Filesystem/Local' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/Gestures/DoubleTap' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/Gestures/Dragging' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/Gestures/LongPress' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/Gestures/Pinch' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/Gestures/SingleTap' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/Gestures/Swipe' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/Gestures/TouchCancel' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/Gestures/TouchEnd' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/Gestures/TouchMove' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/Gestures/TouchStart' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/Gestures/TwoFingerTap' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/has' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/image' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/include' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/lang' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/Layouts' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/Layouts/Base' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/Layouts/Composite' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/Layouts/ConstrainingHorizontal' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/Layouts/ConstrainingVertical' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/Layouts/Horizontal' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/Layouts/Vertical' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/Map/Google' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/ready' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/string' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/style' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/text' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/UI/Element' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/UI/FontWidget' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/UI/KineticScrollView' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/UI/SuperView' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/UI/TextBox' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/UI/WebViewBridge' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/_/UI/Widget' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/Accelerometer' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/Analytics' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/API' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/App' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/App/Properties' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/Blob' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/BlobStream' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/Buffer' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/BufferStream' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/Codec' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/Facebook' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/Facebook/LoginButton' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/Filesystem' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/Filesystem/File' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/Filesystem/FileStream' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/Geolocation' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/Gesture' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/IOStream' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/Locale' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/Map' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/Map/Annotation' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/Map/View' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/Media' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/Media/AudioPlayer' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/Media/Sound' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/Media/VideoPlayer' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/Network' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/Network/HTTPClient' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/Platform' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/Platform/DisplayCaps' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/UI' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/UI/2DMatrix' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/UI/ActivityIndicator' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/UI/ActivityIndicatorStyle' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/UI/AlertDialog' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/UI/Animation' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/UI/Button' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/UI/Clipboard' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/UI/EmailDialog' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/UI/ImageView' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/UI/Label' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/UI/MobileWeb' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/UI/MobileWeb/NavigationGroup' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/UI/MobileWeb/TableViewSeparatorStyle' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/UI/OptionDialog' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/UI/Picker' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/UI/PickerColumn' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/UI/PickerRow' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/UI/ProgressBar' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/UI/ScrollableView' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/UI/ScrollView' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/UI/Slider' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/UI/Switch' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/UI/Tab' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/UI/TabGroup' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/UI/TableView' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/UI/TableViewRow' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/UI/TableViewSection' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/UI/TextArea' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/UI/TextField' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/UI/View' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/UI/WebView' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/UI/Window' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/Utils' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/XML' {
  declare module.exports: any;
}

declare module 'pubnub/resources/titanium/titanium/Ti/Yahoo' {
  declare module.exports: any;
}

declare module 'pubnub/src/core/components/config' {
  declare module.exports: any;
}

declare module 'pubnub/src/core/components/cryptography/hmac-sha256' {
  declare module.exports: any;
}

declare module 'pubnub/src/core/components/cryptography/index' {
  declare module.exports: any;
}

declare module 'pubnub/src/core/components/endpoint' {
  declare module.exports: any;
}

declare module 'pubnub/src/core/components/listener_manager' {
  declare module.exports: any;
}

declare module 'pubnub/src/core/components/reconnection_manager' {
  declare module.exports: any;
}

declare module 'pubnub/src/core/components/subscription_manager' {
  declare module.exports: any;
}

declare module 'pubnub/src/core/constants/categories' {
  declare module.exports: any;
}

declare module 'pubnub/src/core/constants/operations' {
  declare module.exports: any;
}

declare module 'pubnub/src/core/endpoints/access_manager/audit' {
  declare module.exports: any;
}

declare module 'pubnub/src/core/endpoints/access_manager/grant' {
  declare module.exports: any;
}

declare module 'pubnub/src/core/endpoints/channel_groups/add_channels' {
  declare module.exports: any;
}

declare module 'pubnub/src/core/endpoints/channel_groups/delete_group' {
  declare module.exports: any;
}

declare module 'pubnub/src/core/endpoints/channel_groups/list_channels' {
  declare module.exports: any;
}

declare module 'pubnub/src/core/endpoints/channel_groups/list_groups' {
  declare module.exports: any;
}

declare module 'pubnub/src/core/endpoints/channel_groups/remove_channels' {
  declare module.exports: any;
}

declare module 'pubnub/src/core/endpoints/fetch_messages' {
  declare module.exports: any;
}

declare module 'pubnub/src/core/endpoints/history' {
  declare module.exports: any;
}

declare module 'pubnub/src/core/endpoints/presence/get_state' {
  declare module.exports: any;
}

declare module 'pubnub/src/core/endpoints/presence/heartbeat' {
  declare module.exports: any;
}

declare module 'pubnub/src/core/endpoints/presence/here_now' {
  declare module.exports: any;
}

declare module 'pubnub/src/core/endpoints/presence/leave' {
  declare module.exports: any;
}

declare module 'pubnub/src/core/endpoints/presence/set_state' {
  declare module.exports: any;
}

declare module 'pubnub/src/core/endpoints/presence/where_now' {
  declare module.exports: any;
}

declare module 'pubnub/src/core/endpoints/publish' {
  declare module.exports: any;
}

declare module 'pubnub/src/core/endpoints/push/add_push_channels' {
  declare module.exports: any;
}

declare module 'pubnub/src/core/endpoints/push/list_push_channels' {
  declare module.exports: any;
}

declare module 'pubnub/src/core/endpoints/push/remove_device' {
  declare module.exports: any;
}

declare module 'pubnub/src/core/endpoints/push/remove_push_channels' {
  declare module.exports: any;
}

declare module 'pubnub/src/core/endpoints/subscribe' {
  declare module.exports: any;
}

declare module 'pubnub/src/core/endpoints/time' {
  declare module.exports: any;
}

declare module 'pubnub/src/core/flow_interfaces' {
  declare module.exports: any;
}

declare module 'pubnub/src/core/pubnub-common' {
  declare module.exports: any;
}

declare module 'pubnub/src/core/utils' {
  declare module.exports: any;
}

declare module 'pubnub/src/db/common' {
  declare module.exports: any;
}

declare module 'pubnub/src/db/web' {
  declare module.exports: any;
}

declare module 'pubnub/src/networking/index' {
  declare module.exports: any;
}

declare module 'pubnub/src/networking/modules/node' {
  declare module.exports: any;
}

declare module 'pubnub/src/networking/modules/react_native' {
  declare module.exports: any;
}

declare module 'pubnub/src/networking/modules/titanium' {
  declare module.exports: any;
}

declare module 'pubnub/src/networking/modules/web-node' {
  declare module.exports: any;
}

declare module 'pubnub/src/networking/utils' {
  declare module.exports: any;
}

declare module 'pubnub/src/node/index' {
  declare module.exports: any;
}

declare module 'pubnub/src/react_native/index' {
  declare module.exports: any;
}

declare module 'pubnub/src/titanium/index' {
  declare module.exports: any;
}

declare module 'pubnub/src/web/index' {
  declare module.exports: any;
}

declare module 'pubnub/test/dist/react-native.test' {
  declare module.exports: any;
}

declare module 'pubnub/test/dist/web-titanium.test' {
  declare module.exports: any;
}

declare module 'pubnub/test/integration/components/config.test' {
  declare module.exports: any;
}

declare module 'pubnub/test/integration/components/networking.test' {
  declare module.exports: any;
}

declare module 'pubnub/test/integration/components/reconnection_manager.test' {
  declare module.exports: any;
}

declare module 'pubnub/test/integration/components/subscription_manager.test' {
  declare module.exports: any;
}

declare module 'pubnub/test/integration/endpoints/access.test' {
  declare module.exports: any;
}

declare module 'pubnub/test/integration/endpoints/channel_groups.test' {
  declare module.exports: any;
}

declare module 'pubnub/test/integration/endpoints/fetch_messages.test' {
  declare module.exports: any;
}

declare module 'pubnub/test/integration/endpoints/history.test' {
  declare module.exports: any;
}

declare module 'pubnub/test/integration/endpoints/presence.test' {
  declare module.exports: any;
}

declare module 'pubnub/test/integration/endpoints/publish.test' {
  declare module.exports: any;
}

declare module 'pubnub/test/integration/endpoints/push.test' {
  declare module.exports: any;
}

declare module 'pubnub/test/integration/endpoints/subscribe.test' {
  declare module.exports: any;
}

declare module 'pubnub/test/integration/endpoints/time.test' {
  declare module.exports: any;
}

declare module 'pubnub/test/integration/operations/heartbeat.test' {
  declare module.exports: any;
}

declare module 'pubnub/test/integration/operations/stateSetting.test' {
  declare module.exports: any;
}

declare module 'pubnub/test/integration/operations/unsubscribe.test' {
  declare module.exports: any;
}

declare module 'pubnub/test/release/release.test' {
  declare module.exports: any;
}

declare module 'pubnub/test/unit/common.test' {
  declare module.exports: any;
}

declare module 'pubnub/test/unit/listener_manager.test' {
  declare module.exports: any;
}

declare module 'pubnub/test/utils' {
  declare module.exports: any;
}

declare module 'pubnub/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pubnub/dist/titanium/pubnub.js' {
  declare module.exports: $Exports<'pubnub/dist/titanium/pubnub'>;
}
declare module 'pubnub/dist/titanium/pubnub.min.js' {
  declare module.exports: $Exports<'pubnub/dist/titanium/pubnub.min'>;
}
declare module 'pubnub/dist/web/pubnub.js' {
  declare module.exports: $Exports<'pubnub/dist/web/pubnub'>;
}
declare module 'pubnub/dist/web/pubnub.min.js' {
  declare module.exports: $Exports<'pubnub/dist/web/pubnub.min'>;
}
declare module 'pubnub/gulpfile.babel.js' {
  declare module.exports: $Exports<'pubnub/gulpfile.babel'>;
}
declare module 'pubnub/karma/coverage/PhantomJS 2.1.1 (Mac OS X 0.0.0)/lcov-report/prettify.js' {
  declare module.exports: $Exports<'pubnub/karma/coverage/PhantomJS 2.1.1 (Mac OS X 0.0.0)/lcov-report/prettify'>;
}
declare module 'pubnub/karma/coverage/PhantomJS 2.1.1 (Mac OS X 0.0.0)/lcov-report/sorter.js' {
  declare module.exports: $Exports<'pubnub/karma/coverage/PhantomJS 2.1.1 (Mac OS X 0.0.0)/lcov-report/sorter'>;
}
declare module 'pubnub/karma/coverage/PhantomJS 2.1.1 (Mac OS X 0.0.0)/prettify.js' {
  declare module.exports: $Exports<'pubnub/karma/coverage/PhantomJS 2.1.1 (Mac OS X 0.0.0)/prettify'>;
}
declare module 'pubnub/karma/coverage/PhantomJS 2.1.1 (Mac OS X 0.0.0)/sorter.js' {
  declare module.exports: $Exports<'pubnub/karma/coverage/PhantomJS 2.1.1 (Mac OS X 0.0.0)/sorter'>;
}
declare module 'pubnub/karma/titanium.config.js' {
  declare module.exports: $Exports<'pubnub/karma/titanium.config'>;
}
declare module 'pubnub/karma/web.config.js' {
  declare module.exports: $Exports<'pubnub/karma/web.config'>;
}
declare module 'pubnub/lib/core/components/config.js' {
  declare module.exports: $Exports<'pubnub/lib/core/components/config'>;
}
declare module 'pubnub/lib/core/components/cryptography/hmac-sha256.js' {
  declare module.exports: $Exports<'pubnub/lib/core/components/cryptography/hmac-sha256'>;
}
declare module 'pubnub/lib/core/components/cryptography/index.js' {
  declare module.exports: $Exports<'pubnub/lib/core/components/cryptography/index'>;
}
declare module 'pubnub/lib/core/components/endpoint.js' {
  declare module.exports: $Exports<'pubnub/lib/core/components/endpoint'>;
}
declare module 'pubnub/lib/core/components/listener_manager.js' {
  declare module.exports: $Exports<'pubnub/lib/core/components/listener_manager'>;
}
declare module 'pubnub/lib/core/components/reconnection_manager.js' {
  declare module.exports: $Exports<'pubnub/lib/core/components/reconnection_manager'>;
}
declare module 'pubnub/lib/core/components/subscription_manager.js' {
  declare module.exports: $Exports<'pubnub/lib/core/components/subscription_manager'>;
}
declare module 'pubnub/lib/core/constants/categories.js' {
  declare module.exports: $Exports<'pubnub/lib/core/constants/categories'>;
}
declare module 'pubnub/lib/core/constants/operations.js' {
  declare module.exports: $Exports<'pubnub/lib/core/constants/operations'>;
}
declare module 'pubnub/lib/core/endpoints/access_manager/audit.js' {
  declare module.exports: $Exports<'pubnub/lib/core/endpoints/access_manager/audit'>;
}
declare module 'pubnub/lib/core/endpoints/access_manager/grant.js' {
  declare module.exports: $Exports<'pubnub/lib/core/endpoints/access_manager/grant'>;
}
declare module 'pubnub/lib/core/endpoints/channel_groups/add_channels.js' {
  declare module.exports: $Exports<'pubnub/lib/core/endpoints/channel_groups/add_channels'>;
}
declare module 'pubnub/lib/core/endpoints/channel_groups/delete_group.js' {
  declare module.exports: $Exports<'pubnub/lib/core/endpoints/channel_groups/delete_group'>;
}
declare module 'pubnub/lib/core/endpoints/channel_groups/list_channels.js' {
  declare module.exports: $Exports<'pubnub/lib/core/endpoints/channel_groups/list_channels'>;
}
declare module 'pubnub/lib/core/endpoints/channel_groups/list_groups.js' {
  declare module.exports: $Exports<'pubnub/lib/core/endpoints/channel_groups/list_groups'>;
}
declare module 'pubnub/lib/core/endpoints/channel_groups/remove_channels.js' {
  declare module.exports: $Exports<'pubnub/lib/core/endpoints/channel_groups/remove_channels'>;
}
declare module 'pubnub/lib/core/endpoints/fetch_messages.js' {
  declare module.exports: $Exports<'pubnub/lib/core/endpoints/fetch_messages'>;
}
declare module 'pubnub/lib/core/endpoints/history.js' {
  declare module.exports: $Exports<'pubnub/lib/core/endpoints/history'>;
}
declare module 'pubnub/lib/core/endpoints/presence/get_state.js' {
  declare module.exports: $Exports<'pubnub/lib/core/endpoints/presence/get_state'>;
}
declare module 'pubnub/lib/core/endpoints/presence/heartbeat.js' {
  declare module.exports: $Exports<'pubnub/lib/core/endpoints/presence/heartbeat'>;
}
declare module 'pubnub/lib/core/endpoints/presence/here_now.js' {
  declare module.exports: $Exports<'pubnub/lib/core/endpoints/presence/here_now'>;
}
declare module 'pubnub/lib/core/endpoints/presence/leave.js' {
  declare module.exports: $Exports<'pubnub/lib/core/endpoints/presence/leave'>;
}
declare module 'pubnub/lib/core/endpoints/presence/set_state.js' {
  declare module.exports: $Exports<'pubnub/lib/core/endpoints/presence/set_state'>;
}
declare module 'pubnub/lib/core/endpoints/presence/where_now.js' {
  declare module.exports: $Exports<'pubnub/lib/core/endpoints/presence/where_now'>;
}
declare module 'pubnub/lib/core/endpoints/publish.js' {
  declare module.exports: $Exports<'pubnub/lib/core/endpoints/publish'>;
}
declare module 'pubnub/lib/core/endpoints/push/add_push_channels.js' {
  declare module.exports: $Exports<'pubnub/lib/core/endpoints/push/add_push_channels'>;
}
declare module 'pubnub/lib/core/endpoints/push/list_push_channels.js' {
  declare module.exports: $Exports<'pubnub/lib/core/endpoints/push/list_push_channels'>;
}
declare module 'pubnub/lib/core/endpoints/push/remove_device.js' {
  declare module.exports: $Exports<'pubnub/lib/core/endpoints/push/remove_device'>;
}
declare module 'pubnub/lib/core/endpoints/push/remove_push_channels.js' {
  declare module.exports: $Exports<'pubnub/lib/core/endpoints/push/remove_push_channels'>;
}
declare module 'pubnub/lib/core/endpoints/subscribe.js' {
  declare module.exports: $Exports<'pubnub/lib/core/endpoints/subscribe'>;
}
declare module 'pubnub/lib/core/endpoints/time.js' {
  declare module.exports: $Exports<'pubnub/lib/core/endpoints/time'>;
}
declare module 'pubnub/lib/core/flow_interfaces.js' {
  declare module.exports: $Exports<'pubnub/lib/core/flow_interfaces'>;
}
declare module 'pubnub/lib/core/pubnub-common.js' {
  declare module.exports: $Exports<'pubnub/lib/core/pubnub-common'>;
}
declare module 'pubnub/lib/core/utils.js' {
  declare module.exports: $Exports<'pubnub/lib/core/utils'>;
}
declare module 'pubnub/lib/db/common.js' {
  declare module.exports: $Exports<'pubnub/lib/db/common'>;
}
declare module 'pubnub/lib/db/web.js' {
  declare module.exports: $Exports<'pubnub/lib/db/web'>;
}
declare module 'pubnub/lib/networking/index.js' {
  declare module.exports: $Exports<'pubnub/lib/networking/index'>;
}
declare module 'pubnub/lib/networking/modules/node.js' {
  declare module.exports: $Exports<'pubnub/lib/networking/modules/node'>;
}
declare module 'pubnub/lib/networking/modules/react_native.js' {
  declare module.exports: $Exports<'pubnub/lib/networking/modules/react_native'>;
}
declare module 'pubnub/lib/networking/modules/titanium.js' {
  declare module.exports: $Exports<'pubnub/lib/networking/modules/titanium'>;
}
declare module 'pubnub/lib/networking/modules/web-node.js' {
  declare module.exports: $Exports<'pubnub/lib/networking/modules/web-node'>;
}
declare module 'pubnub/lib/networking/utils.js' {
  declare module.exports: $Exports<'pubnub/lib/networking/utils'>;
}
declare module 'pubnub/lib/node/index.js' {
  declare module.exports: $Exports<'pubnub/lib/node/index'>;
}
declare module 'pubnub/lib/react_native/index.js' {
  declare module.exports: $Exports<'pubnub/lib/react_native/index'>;
}
declare module 'pubnub/lib/titanium/index.js' {
  declare module.exports: $Exports<'pubnub/lib/titanium/index'>;
}
declare module 'pubnub/lib/web/index.js' {
  declare module.exports: $Exports<'pubnub/lib/web/index'>;
}
declare module 'pubnub/resources/titanium/titanium.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/analytics.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/analytics'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/browser.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/browser'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/colors.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/colors'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/css.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/css'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/declare.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/declare'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/dom.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/dom'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/encoding.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/encoding'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/event.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/event'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/Evented.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/Evented'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/Filesystem/Local.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/Filesystem/Local'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/Gestures/DoubleTap.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/Gestures/DoubleTap'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/Gestures/Dragging.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/Gestures/Dragging'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/Gestures/LongPress.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/Gestures/LongPress'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/Gestures/Pinch.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/Gestures/Pinch'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/Gestures/SingleTap.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/Gestures/SingleTap'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/Gestures/Swipe.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/Gestures/Swipe'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/Gestures/TouchCancel.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/Gestures/TouchCancel'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/Gestures/TouchEnd.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/Gestures/TouchEnd'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/Gestures/TouchMove.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/Gestures/TouchMove'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/Gestures/TouchStart.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/Gestures/TouchStart'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/Gestures/TwoFingerTap.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/Gestures/TwoFingerTap'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/has.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/has'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/image.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/image'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/include.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/include'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/lang.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/lang'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/Layouts.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/Layouts'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/Layouts/Base.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/Layouts/Base'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/Layouts/Composite.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/Layouts/Composite'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/Layouts/ConstrainingHorizontal.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/Layouts/ConstrainingHorizontal'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/Layouts/ConstrainingVertical.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/Layouts/ConstrainingVertical'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/Layouts/Horizontal.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/Layouts/Horizontal'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/Layouts/Vertical.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/Layouts/Vertical'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/Map/Google.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/Map/Google'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/ready.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/ready'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/string.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/string'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/style.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/style'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/text.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/text'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/UI/Element.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/UI/Element'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/UI/FontWidget.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/UI/FontWidget'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/UI/KineticScrollView.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/UI/KineticScrollView'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/UI/SuperView.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/UI/SuperView'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/UI/TextBox.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/UI/TextBox'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/UI/WebViewBridge.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/UI/WebViewBridge'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/_/UI/Widget.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/_/UI/Widget'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/Accelerometer.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/Accelerometer'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/Analytics.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/Analytics'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/API.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/API'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/App.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/App'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/App/Properties.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/App/Properties'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/Blob.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/Blob'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/BlobStream.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/BlobStream'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/Buffer.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/Buffer'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/BufferStream.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/BufferStream'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/Codec.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/Codec'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/Facebook.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/Facebook'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/Facebook/LoginButton.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/Facebook/LoginButton'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/Filesystem.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/Filesystem'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/Filesystem/File.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/Filesystem/File'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/Filesystem/FileStream.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/Filesystem/FileStream'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/Geolocation.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/Geolocation'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/Gesture.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/Gesture'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/IOStream.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/IOStream'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/Locale.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/Locale'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/Map.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/Map'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/Map/Annotation.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/Map/Annotation'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/Map/View.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/Map/View'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/Media.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/Media'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/Media/AudioPlayer.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/Media/AudioPlayer'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/Media/Sound.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/Media/Sound'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/Media/VideoPlayer.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/Media/VideoPlayer'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/Network.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/Network'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/Network/HTTPClient.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/Network/HTTPClient'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/Platform.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/Platform'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/Platform/DisplayCaps.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/Platform/DisplayCaps'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/UI.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/UI'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/UI/2DMatrix.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/UI/2DMatrix'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/UI/ActivityIndicator.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/UI/ActivityIndicator'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/UI/ActivityIndicatorStyle.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/UI/ActivityIndicatorStyle'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/UI/AlertDialog.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/UI/AlertDialog'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/UI/Animation.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/UI/Animation'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/UI/Button.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/UI/Button'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/UI/Clipboard.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/UI/Clipboard'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/UI/EmailDialog.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/UI/EmailDialog'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/UI/ImageView.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/UI/ImageView'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/UI/Label.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/UI/Label'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/UI/MobileWeb.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/UI/MobileWeb'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/UI/MobileWeb/NavigationGroup.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/UI/MobileWeb/NavigationGroup'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/UI/MobileWeb/TableViewSeparatorStyle.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/UI/MobileWeb/TableViewSeparatorStyle'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/UI/OptionDialog.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/UI/OptionDialog'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/UI/Picker.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/UI/Picker'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/UI/PickerColumn.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/UI/PickerColumn'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/UI/PickerRow.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/UI/PickerRow'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/UI/ProgressBar.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/UI/ProgressBar'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/UI/ScrollableView.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/UI/ScrollableView'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/UI/ScrollView.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/UI/ScrollView'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/UI/Slider.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/UI/Slider'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/UI/Switch.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/UI/Switch'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/UI/Tab.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/UI/Tab'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/UI/TabGroup.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/UI/TabGroup'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/UI/TableView.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/UI/TableView'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/UI/TableViewRow.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/UI/TableViewRow'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/UI/TableViewSection.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/UI/TableViewSection'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/UI/TextArea.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/UI/TextArea'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/UI/TextField.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/UI/TextField'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/UI/View.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/UI/View'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/UI/WebView.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/UI/WebView'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/UI/Window.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/UI/Window'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/Utils.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/Utils'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/XML.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/XML'>;
}
declare module 'pubnub/resources/titanium/titanium/Ti/Yahoo.js' {
  declare module.exports: $Exports<'pubnub/resources/titanium/titanium/Ti/Yahoo'>;
}
declare module 'pubnub/src/core/components/config.js' {
  declare module.exports: $Exports<'pubnub/src/core/components/config'>;
}
declare module 'pubnub/src/core/components/cryptography/hmac-sha256.js' {
  declare module.exports: $Exports<'pubnub/src/core/components/cryptography/hmac-sha256'>;
}
declare module 'pubnub/src/core/components/cryptography/index.js' {
  declare module.exports: $Exports<'pubnub/src/core/components/cryptography/index'>;
}
declare module 'pubnub/src/core/components/endpoint.js' {
  declare module.exports: $Exports<'pubnub/src/core/components/endpoint'>;
}
declare module 'pubnub/src/core/components/listener_manager.js' {
  declare module.exports: $Exports<'pubnub/src/core/components/listener_manager'>;
}
declare module 'pubnub/src/core/components/reconnection_manager.js' {
  declare module.exports: $Exports<'pubnub/src/core/components/reconnection_manager'>;
}
declare module 'pubnub/src/core/components/subscription_manager.js' {
  declare module.exports: $Exports<'pubnub/src/core/components/subscription_manager'>;
}
declare module 'pubnub/src/core/constants/categories.js' {
  declare module.exports: $Exports<'pubnub/src/core/constants/categories'>;
}
declare module 'pubnub/src/core/constants/operations.js' {
  declare module.exports: $Exports<'pubnub/src/core/constants/operations'>;
}
declare module 'pubnub/src/core/endpoints/access_manager/audit.js' {
  declare module.exports: $Exports<'pubnub/src/core/endpoints/access_manager/audit'>;
}
declare module 'pubnub/src/core/endpoints/access_manager/grant.js' {
  declare module.exports: $Exports<'pubnub/src/core/endpoints/access_manager/grant'>;
}
declare module 'pubnub/src/core/endpoints/channel_groups/add_channels.js' {
  declare module.exports: $Exports<'pubnub/src/core/endpoints/channel_groups/add_channels'>;
}
declare module 'pubnub/src/core/endpoints/channel_groups/delete_group.js' {
  declare module.exports: $Exports<'pubnub/src/core/endpoints/channel_groups/delete_group'>;
}
declare module 'pubnub/src/core/endpoints/channel_groups/list_channels.js' {
  declare module.exports: $Exports<'pubnub/src/core/endpoints/channel_groups/list_channels'>;
}
declare module 'pubnub/src/core/endpoints/channel_groups/list_groups.js' {
  declare module.exports: $Exports<'pubnub/src/core/endpoints/channel_groups/list_groups'>;
}
declare module 'pubnub/src/core/endpoints/channel_groups/remove_channels.js' {
  declare module.exports: $Exports<'pubnub/src/core/endpoints/channel_groups/remove_channels'>;
}
declare module 'pubnub/src/core/endpoints/fetch_messages.js' {
  declare module.exports: $Exports<'pubnub/src/core/endpoints/fetch_messages'>;
}
declare module 'pubnub/src/core/endpoints/history.js' {
  declare module.exports: $Exports<'pubnub/src/core/endpoints/history'>;
}
declare module 'pubnub/src/core/endpoints/presence/get_state.js' {
  declare module.exports: $Exports<'pubnub/src/core/endpoints/presence/get_state'>;
}
declare module 'pubnub/src/core/endpoints/presence/heartbeat.js' {
  declare module.exports: $Exports<'pubnub/src/core/endpoints/presence/heartbeat'>;
}
declare module 'pubnub/src/core/endpoints/presence/here_now.js' {
  declare module.exports: $Exports<'pubnub/src/core/endpoints/presence/here_now'>;
}
declare module 'pubnub/src/core/endpoints/presence/leave.js' {
  declare module.exports: $Exports<'pubnub/src/core/endpoints/presence/leave'>;
}
declare module 'pubnub/src/core/endpoints/presence/set_state.js' {
  declare module.exports: $Exports<'pubnub/src/core/endpoints/presence/set_state'>;
}
declare module 'pubnub/src/core/endpoints/presence/where_now.js' {
  declare module.exports: $Exports<'pubnub/src/core/endpoints/presence/where_now'>;
}
declare module 'pubnub/src/core/endpoints/publish.js' {
  declare module.exports: $Exports<'pubnub/src/core/endpoints/publish'>;
}
declare module 'pubnub/src/core/endpoints/push/add_push_channels.js' {
  declare module.exports: $Exports<'pubnub/src/core/endpoints/push/add_push_channels'>;
}
declare module 'pubnub/src/core/endpoints/push/list_push_channels.js' {
  declare module.exports: $Exports<'pubnub/src/core/endpoints/push/list_push_channels'>;
}
declare module 'pubnub/src/core/endpoints/push/remove_device.js' {
  declare module.exports: $Exports<'pubnub/src/core/endpoints/push/remove_device'>;
}
declare module 'pubnub/src/core/endpoints/push/remove_push_channels.js' {
  declare module.exports: $Exports<'pubnub/src/core/endpoints/push/remove_push_channels'>;
}
declare module 'pubnub/src/core/endpoints/subscribe.js' {
  declare module.exports: $Exports<'pubnub/src/core/endpoints/subscribe'>;
}
declare module 'pubnub/src/core/endpoints/time.js' {
  declare module.exports: $Exports<'pubnub/src/core/endpoints/time'>;
}
declare module 'pubnub/src/core/flow_interfaces.js' {
  declare module.exports: $Exports<'pubnub/src/core/flow_interfaces'>;
}
declare module 'pubnub/src/core/pubnub-common.js' {
  declare module.exports: $Exports<'pubnub/src/core/pubnub-common'>;
}
declare module 'pubnub/src/core/utils.js' {
  declare module.exports: $Exports<'pubnub/src/core/utils'>;
}
declare module 'pubnub/src/db/common.js' {
  declare module.exports: $Exports<'pubnub/src/db/common'>;
}
declare module 'pubnub/src/db/web.js' {
  declare module.exports: $Exports<'pubnub/src/db/web'>;
}
declare module 'pubnub/src/networking/index.js' {
  declare module.exports: $Exports<'pubnub/src/networking/index'>;
}
declare module 'pubnub/src/networking/modules/node.js' {
  declare module.exports: $Exports<'pubnub/src/networking/modules/node'>;
}
declare module 'pubnub/src/networking/modules/react_native.js' {
  declare module.exports: $Exports<'pubnub/src/networking/modules/react_native'>;
}
declare module 'pubnub/src/networking/modules/titanium.js' {
  declare module.exports: $Exports<'pubnub/src/networking/modules/titanium'>;
}
declare module 'pubnub/src/networking/modules/web-node.js' {
  declare module.exports: $Exports<'pubnub/src/networking/modules/web-node'>;
}
declare module 'pubnub/src/networking/utils.js' {
  declare module.exports: $Exports<'pubnub/src/networking/utils'>;
}
declare module 'pubnub/src/node/index.js' {
  declare module.exports: $Exports<'pubnub/src/node/index'>;
}
declare module 'pubnub/src/react_native/index.js' {
  declare module.exports: $Exports<'pubnub/src/react_native/index'>;
}
declare module 'pubnub/src/titanium/index.js' {
  declare module.exports: $Exports<'pubnub/src/titanium/index'>;
}
declare module 'pubnub/src/web/index.js' {
  declare module.exports: $Exports<'pubnub/src/web/index'>;
}
declare module 'pubnub/test/dist/react-native.test.js' {
  declare module.exports: $Exports<'pubnub/test/dist/react-native.test'>;
}
declare module 'pubnub/test/dist/web-titanium.test.js' {
  declare module.exports: $Exports<'pubnub/test/dist/web-titanium.test'>;
}
declare module 'pubnub/test/integration/components/config.test.js' {
  declare module.exports: $Exports<'pubnub/test/integration/components/config.test'>;
}
declare module 'pubnub/test/integration/components/networking.test.js' {
  declare module.exports: $Exports<'pubnub/test/integration/components/networking.test'>;
}
declare module 'pubnub/test/integration/components/reconnection_manager.test.js' {
  declare module.exports: $Exports<'pubnub/test/integration/components/reconnection_manager.test'>;
}
declare module 'pubnub/test/integration/components/subscription_manager.test.js' {
  declare module.exports: $Exports<'pubnub/test/integration/components/subscription_manager.test'>;
}
declare module 'pubnub/test/integration/endpoints/access.test.js' {
  declare module.exports: $Exports<'pubnub/test/integration/endpoints/access.test'>;
}
declare module 'pubnub/test/integration/endpoints/channel_groups.test.js' {
  declare module.exports: $Exports<'pubnub/test/integration/endpoints/channel_groups.test'>;
}
declare module 'pubnub/test/integration/endpoints/fetch_messages.test.js' {
  declare module.exports: $Exports<'pubnub/test/integration/endpoints/fetch_messages.test'>;
}
declare module 'pubnub/test/integration/endpoints/history.test.js' {
  declare module.exports: $Exports<'pubnub/test/integration/endpoints/history.test'>;
}
declare module 'pubnub/test/integration/endpoints/presence.test.js' {
  declare module.exports: $Exports<'pubnub/test/integration/endpoints/presence.test'>;
}
declare module 'pubnub/test/integration/endpoints/publish.test.js' {
  declare module.exports: $Exports<'pubnub/test/integration/endpoints/publish.test'>;
}
declare module 'pubnub/test/integration/endpoints/push.test.js' {
  declare module.exports: $Exports<'pubnub/test/integration/endpoints/push.test'>;
}
declare module 'pubnub/test/integration/endpoints/subscribe.test.js' {
  declare module.exports: $Exports<'pubnub/test/integration/endpoints/subscribe.test'>;
}
declare module 'pubnub/test/integration/endpoints/time.test.js' {
  declare module.exports: $Exports<'pubnub/test/integration/endpoints/time.test'>;
}
declare module 'pubnub/test/integration/operations/heartbeat.test.js' {
  declare module.exports: $Exports<'pubnub/test/integration/operations/heartbeat.test'>;
}
declare module 'pubnub/test/integration/operations/stateSetting.test.js' {
  declare module.exports: $Exports<'pubnub/test/integration/operations/stateSetting.test'>;
}
declare module 'pubnub/test/integration/operations/unsubscribe.test.js' {
  declare module.exports: $Exports<'pubnub/test/integration/operations/unsubscribe.test'>;
}
declare module 'pubnub/test/release/release.test.js' {
  declare module.exports: $Exports<'pubnub/test/release/release.test'>;
}
declare module 'pubnub/test/unit/common.test.js' {
  declare module.exports: $Exports<'pubnub/test/unit/common.test'>;
}
declare module 'pubnub/test/unit/listener_manager.test.js' {
  declare module.exports: $Exports<'pubnub/test/unit/listener_manager.test'>;
}
declare module 'pubnub/test/utils.js' {
  declare module.exports: $Exports<'pubnub/test/utils'>;
}
declare module 'pubnub/webpack.config.js' {
  declare module.exports: $Exports<'pubnub/webpack.config'>;
}
