apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: snack
spec:
  rules:
  - host: snack.expo.test
    http:
      paths:
      - backend:
          serviceName: snack
          servicePort: 80
        path: /
