apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
bases:
- ../staging
patches:
- patch: |-
    - op: remove
      path: /spec/template/spec/containers/0/resources
  target:
    group: apps
    kind: Deployment
    name: snack
    version: v1
configMapGenerator:
- name: snack
  behavior: merge
  envs:
  - snack.env
