import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        {/*meta.map((metaProps, index) => (
          <meta key={index} {...metaProps} />
        ))*/}
        <meta
          name="google-site-verification"
          content="Fh25fNM-buRYptb-TO6MVgOjXGzdhmAnRgIC7sdrmbw"
        />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300,500,600"
        />
        {/*<link rel="stylesheet" href={resources.normalize} />*/}
        {/*<script
          dangerouslySetInnerHTML={{
            __html: `
               if (window.location.search.indexOf('hideQueryParams=true') >= 0) {
                 history.replaceState(null, document.title, window.location.pathname);
               }
               window.__INITIAL_DATA__ = ${jsesc(
                 {
                   data,
                   splitTestSettings,
                   queryParams,
                   // TODO: Remove `postData` in the summer of 2021. `postData` was replaced
                   // by `queryParams` (which unifies post- and query data). This variable was
                   // re-added to support older cached clients, which have not yet been updated
                   postData: queryParams,
                 },
                 {
                   quotes: 'double',
                   isScriptContext: true,
                 }
               )} `,
          }}
        />*/}
      </Head>
      <main>
        {/* isEmbedded || !isAuthenticated ? (
          <Amplitude />
        ) : (
          <Segment splitTestSettings={splitTestSettings} />
        ) */}
        {/* <GoogleAnalytics propertyId="UA-53647600-5" /> */}
        {/*<ServiceWorkerManager />
              <Provider store={store}>
                <PreferencesProvider cookies={cookies} queryParams={queryParams}>
                  <ThemeProvider>
                    <StaticRouter location={ctx.request.url} context={context}>
                      <ClientRouter data={data} queryParams={queryParams} userAgent={userAgent} />
                    </StaticRouter>
                  </ThemeProvider>
                </PreferencesProvider>
              </Provider>*/}
      </main>
    </>
  );
}
