apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: snackpub
build:
  platforms: ['linux/amd64']
  artifacts:
    - image: gcr.io/exponentjs/snackpub
      sync:
        manual:
        - src: src/**/*
          dest: /snack/app
      docker:
        dockerfile: snackpub/Dockerfile
        buildArgs:
          node_version: 16.14.2
          DEPLOY_ENVIRONMENT: staging
  tagPolicy:
    sha256: {}
  local:
    push: false
manifests:
  kustomize:
    paths:
      - k8s/staging
deploy:
  kubectl: {}
  kubeContext: minikube
profiles:
  - name: prod
    activation:
      - env: ENVIRONMENT=production
    manifests:
      kustomize:
        paths:
        - k8s/production
  - name: staging
    activation:
      - env: ENVIRONMENT=staging
    manifests:
      kustomize:
        paths:
        - k8s/staging
  - name: ci
    activation:
      - env: CI=true
    deploy:
      kubectl: {}
      kubeContext: gke_exponentjs_us-central1_general-central
  - name: main
    activation:
      - env: GITHUB_REF=refs/heads/main
    build:
      local:
        push: true
