apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snackager
spec:
  tls:
  - hosts:
    - staging.snackager.expo.io
    secretName: snackager-tls
  rules:
    - host: staging.snackager.expo.io
      http:
        paths:
        - backend:
            service:
              name: snackager
              port:
                number: 80
          path: /
