apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
bases:
- ../base
- external-secret-env.yaml
- external-secret-private-key.yaml
patchesStrategicMerge:
- service-backend.yaml
configMapGenerator:
- name: snackager-config
  behavior: merge
  envs:
  - snackager.env
secretGenerator:
- name: snackager-config
  behavior: merge
  files:
  - ./external-secret-env.yaml
- name: git-account-credentials
  behavior: merge
  files:
  - ./external-secret-private-key.yaml
