name: Setup Runtime
description: Prepare Runtime in GitHub Actions

inputs:
  node-version:
    description: Version of Node to use
    default: 16.x
  
  expo-version:
    description: Version of Expo CLI to use
    default: latest
  
  expo-token:
    description: Expo authentication token to publish
    required: false

runs:
  using: composite
  steps:
    - name: 🏗 Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: yarn
        cache-dependency-path: runtime/yarn.lock

    - name: 🏗 Setup Expo
      uses: expo/expo-github-action@v7
      with:
        expo-version: ${{ inputs.expo-version }}
        token: ${{ inputs.expo-token }}

    # Runtime is detached from the monorepo, we only need to install this
    - name: 📦 Install dependencies
      run: yarn install --frozen-lockfile --ignore-scripts
      working-directory: runtime
      shell: bash
