name: Setup Runtime
description: Prepare Runtime in GitHub Actions

inputs:
  node-version:
    description: Version of Node to use
    default: 16.x

  expo-version:
    description: Version of Expo CLI to use
    default: latest

runs:
  using: composite
  steps:
    - name: 🏗 Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: yarn
        cache-dependency-path: runtime/yarn.lock

    - name: 🏗 Setup Expo
      uses: expo/expo-github-action@v7
      with:
        expo-version: ${{ inputs.expo-version }}

    - name: 📦 Install monorepo dependencies
      run: yarn install --frozen-lockfile
      shell: bash

    - name: 🛠 Build core packages
      run: yarn build
      shell: bash

    # Runtime is detached from the monorepo, we also need to install this
    - name: 📦 Install runtime dependencies
      run: yarn install --frozen-lockfile
      working-directory: runtime
      shell: bash
