name: Setup Runtime
description: Prepare Runtime in GitHub Actions

inputs:
  node-version:
    description: Version of Node to use
    default: 18.x

  eas-version:
    description: Version of EAS CLI to use
    default: latest

runs:
  using: composite
  steps:
    - name: 🏗 Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: yarn
        cache-dependency-path: runtime/yarn.lock

    - name: 🏗 Setup EAS
      uses: expo/expo-github-action@v8
      with:
        eas-version: ${{ inputs.eas-version }}

    - name: 📦 Install monorepo dependencies
      run: yarn install --frozen-lockfile
      shell: bash

    - name: 🛠 Build core packages
      run: yarn build
      shell: bash

    - name: 🛠 Build babel
      run: yarn && yarn build
      working-directory: packages/snack-babel-standalone
      shell: bash

    # Runtime is detached from the monorepo, we also need to install this
    - name: 📦 Install runtime dependencies
      run: yarn install --frozen-lockfile
      working-directory: runtime
      shell: bash
